/-
Copyright (c) 2025 Davood H. T. Tehrani, David Gross. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Davood H. T. Tehrani, David Gross
-/
import «HyperNat».Ideal

open BooleanIdeal

/--
`HypNat I` is the type of hypernatural numbers associated to the ideal `I`,
defined as sequences `ℕ → ℕ` modulo equality outside an I-small set.

If `I` is `PrincipalIdeal n`, generated by a point `n`, then the quotient collapses:
two sequences are equivalent precisely when they agree at that single index.
The quotient is canonically isomorphic to `ℕ` itself. There are no nonstandard elements.

If `I` is a `NPPIdeal`, then the quotient is an ultrapower of `ℕ`.
In that case hypernatural numbers with infinitesimals and infinite elements are obtained
and Łoś theorem holds.
-/
abbrev HypNat (I : BooleanIdeal) := Quotient (BooleanIdeal.Setoid)

notation:max "⟦" a "⟧_" I:max => Quotient.mk (BooleanIdeal.Setoid (I := I)) a

namespace HypNat

def seq_zero : (ℕ → ℕ) := fun _ => Nat.zero

def seq_succ : (ℕ → ℕ) → (ℕ → ℕ) := fun a i => Nat.succ (a i)

def seq_add : (ℕ → ℕ) → (ℕ → ℕ) → (ℕ → ℕ) := fun a b => fun i => Nat.add (a i) (b i)

def seq_mul : (ℕ → ℕ) → (ℕ → ℕ) → (ℕ → ℕ) := fun a b => fun i => Nat.mul (a i) (b i)

@[simp] lemma seq_zero_apply (i : ℕ) : seq_zero i = 0 := rfl

@[simp] lemma seq_succ_apply (a : ℕ → ℕ) (i : ℕ) : seq_succ a i = a i + 1 := rfl

@[simp] lemma seq_add_apply (a b : ℕ → ℕ) (i : ℕ) : seq_add a b i = a i + b i := rfl

@[simp] lemma seq_mul_apply (a b : ℕ → ℕ) (i : ℕ) : seq_mul a b i = a i * b i := rfl

lemma seq_succ_resp (I : BooleanIdeal) : ∀ ⦃a b : ℕ → ℕ⦄, a ≈ b → (seq_succ a) ≈ (seq_succ b) := by
  simp

lemma seq_add_resp (I : BooleanIdeal) : ∀ ⦃a₁ a₂ : ℕ → ℕ⦄, a₁ ≈ a₂ →
    ∀ ⦃b₁ b₂ : ℕ → ℕ⦄, b₁ ≈ b₂ → seq_add a₁ b₁ ≈ seq_add a₂ b₂ := by
  intro _ _ ha _ _ hb
  simp_all only [seq_add, Setoid_rel_iff]
  apply downward_closed (I.closed ha hb)
  grind

lemma seq_mul_resp (I : BooleanIdeal) : ∀ ⦃a₁ a₂ : ℕ → ℕ⦄, a₁ ≈ a₂ →
    ∀ ⦃b₁ b₂ : ℕ → ℕ⦄, b₁ ≈ b₂ → seq_mul a₁ b₁ ≈ seq_mul a₂ b₂ := by
  intro _ _ ha _ _ hb
  simp_all only [seq_mul_apply, Setoid_rel_iff]
  apply downward_closed (I.closed ha hb)
  grind

def succ {I} : HypNat I → HypNat I := Quotient.map seq_succ (seq_succ_resp I)

def add {I} : HypNat I → HypNat I → HypNat I := Quotient.map₂ seq_add (seq_add_resp I)

def mul {I} : HypNat I → HypNat I → HypNat I := Quotient.map₂ seq_mul (seq_mul_resp I)

instance zero {I} : Zero (HypNat I) where zero := Quotient.mk' seq_zero

instance {I} : Add (HypNat I)  := ⟨fun a b => add a b⟩

instance {I} : Mul (HypNat I)  := ⟨fun a b => mul a b⟩

instance inhabited {I} : Inhabited (HypNat I) := ⟨zero.zero⟩

variable (a : Nat → Nat) (I : BooleanIdeal)

@[simp] lemma mk_zero {I} : (0 : HypNat I) = ⟦seq_zero⟧_I := rfl

@[simp] lemma mk_succ {I} (a : ℕ → ℕ) : succ ⟦a⟧_I = ⟦seq_succ a⟧_I := rfl

@[simp] lemma mk_add {I} (a b : ℕ → ℕ) : ⟦a⟧_I + ⟦b⟧_I = ⟦seq_add a b⟧_I := rfl

@[simp] lemma mk_mul {I} (a b : ℕ → ℕ) : ⟦a⟧_I * ⟦b⟧_I = ⟦seq_mul a b⟧_I := rfl

end HypNat
