/-
Copyright (c) 2025 Davood H. T. Tehrani, David Gross. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Davood H. T. Tehrani, David Gross
-/
import Mathlib.Logic.Equiv.Set
import Mathlib.Data.SetLike.Basic

open Set

/--
A `BooleanIdeal` is an ideal in the Boolean algebra `𝒫(ℕ)` of subsets of `ℕ`.

Mathematically, an ideal `I ⊆ 𝒫(ℕ)` satisfies:
1. It is nonempty.
2. It is closed under finite unions: if `x, y ∈ I`, then `x ∪ y ∈ I`.
3. It is downward closed: if `x ∈ I` and `z ⊆ x`, then `z ∈ I`.
   Here this is encoded by closure under intersection with arbitrary sets:
   if `x ∈ I`, then `x ∩ z ∈ I` for all `z`.
4. It is proper (nontrivial): `univ ∉ I`.
-/
@[ext] class BooleanIdeal where
  carrier : Set (Set ℕ)
  non_empty : Set.Nonempty carrier
  closed {x y : Set ℕ} : x ∈ carrier → y ∈ carrier → (x ∪ y) ∈ carrier
  absorbing {x z : Set ℕ} : x ∈ carrier → (x ∩ z) ∈ carrier
  non_trivial : univ ∉ carrier

namespace BooleanIdeal

instance : SetLike BooleanIdeal (Set ℕ) where
  coe I := I.carrier
  coe_injective' _ _ _ := by ext; simp_all

/--
`PrincipalIdeal n` is the principal ideal generated by `{n}ᶜ`,
consisting of all subsets of `ℕ` that do not contain `n`.

Equivalently, it is the ideal
  { s ⊆ ℕ | n ∉ s }.
-/
instance PrincipalIdeal (n : ℕ) : BooleanIdeal where
  carrier := { s | n ∉ s }
  closed := by simp_all
  absorbing := by simp_all
  non_trivial := by simp_all
  non_empty := ⟨{n.succ}, by simp⟩

/--
`FiniteIdeal` is the ideal of finite subsets of `ℕ`.

It consists of all `s ⊆ ℕ` that are bounded above,
which is equivalent to finiteness in `ℕ`.
This ideal is proper since `univ` is infinite.
-/
instance FiniteIdeal : BooleanIdeal where
  carrier := { s | ∃ N: ℕ, ∀ n ∈ s, n < N }
  closed hx hy := by
    simp_all only [mem_setOf_eq, mem_union]
    obtain ⟨wx, hwx⟩ := hx
    obtain ⟨wy, hwy⟩ := hy
    use wx + wy
    grind
  absorbing hx := by
    simp_all only [mem_setOf_eq, mem_inter_iff, and_imp]
    let ⟨w, hw⟩ := hx
    exact ⟨w, fun n => fun s => fun _ => hw n s⟩
  non_trivial h := by
    simp only [mem_setOf_eq, mem_univ, forall_const] at h
    obtain ⟨w, hw⟩ := h
    exact (lt_self_iff_false w).mp (hw w)
  non_empty := by
    exists ∅, 0
    simp_all

/-- The empty set belongs to every Boolean ideal. -/
@[simp] lemma empty_mem (I : BooleanIdeal) : ∅ ∈ I := by
  have ⟨w, hw⟩ := I.non_empty
  rw [show ∅ = w ∩ ∅ by simp]
  exact I.absorbing hw

@[simp] lemma downward_closed {x z} {I : BooleanIdeal} : x ∈ I → z ⊆ x → z ∈ I := by
  intro hx hz
  rw [Set.right_eq_inter.mpr hz]
  exact I.absorbing hx

@[simp] lemma undo_union_left {x y} {I : BooleanIdeal} : x ∪ y ∈ I → x ∈ I := fun hu =>
  downward_closed hu Set.subset_union_left

@[simp] lemma undo_union_right {x y} {I : BooleanIdeal} : x ∪ y ∈ I → y ∈ I := fun hu =>
  downward_closed hu Set.subset_union_right

lemma self_compl_not_mem {A : Set ℕ} (I : BooleanIdeal) : A ∪ Aᶜ ∉ I := by
  intro h
  rw [Set.union_comm, Set.compl_union_self A] at h
  exact I.non_trivial h

end BooleanIdeal

open BooleanIdeal

/--
A `PrimeIdeal` is a Boolean ideal satisfying the prime property:

If `x ∩ y ∈ P`, then `x ∈ P` or `y ∈ P`.
-/
@[ext] class PrimeIdeal extends BooleanIdeal where
  is_prime (x y : Set ℕ) : x ∩ y ∈ carrier → x ∈ carrier ∨ y ∈ carrier

namespace PrimeIdeal

instance : SetLike PrimeIdeal (Set ℕ) where
  coe P := P.carrier
  coe_injective' _ _ _ := by ext; simp_all

instance : Coe PrimeIdeal BooleanIdeal where
  coe a := a.toBooleanIdeal

lemma em (p : PrimeIdeal) (A : Set ℕ) : A ∈ p ∨ Aᶜ ∈ p := by
  have h : ∅ ∈ p := empty_mem p
  rw [← Set.compl_inter_self A, Set.inter_comm] at h
  exact p.is_prime A Aᶜ h

lemma mem_iff_compl_not_mem (p : PrimeIdeal) (A : Set ℕ) : A ∈ p ↔ Aᶜ ∉ p :=
  ⟨(fun _ h₁ h₂ => self_compl_not_mem p (p.closed h₁ h₂)) A,
    fun h => (em p A).resolve_right h⟩

end PrimeIdeal

/--
An `NPPIdeal` is a non-principal prime ideal.

It excludes all principal ideals generated by singletons,
that is, for every `n`, the cofinite set `{ i | i ≠ n }`
does not belong to the ideal.
-/
@[ext] class NPPIdeal extends PrimeIdeal where
  is_non_principal : ∀ n : ℕ, { i | i ≠ n} ∉ carrier

namespace NPPIdeal

instance : SetLike NPPIdeal (Set ℕ) where
  coe NP := NP.carrier
  coe_injective' _ _ _ := by ext; simp_all

instance : Coe NPPIdeal PrimeIdeal  where
  coe a := a.toPrimeIdeal

end NPPIdeal

/--
For a Boolean ideal `I`, define `x ~ y` for functions `ℕ → ℕ` by `x ~ y ↔ { i | x i ≠ y i } ∈ I`.
Thus two functions are identified if they differ only on an I-small set.
-/
instance BooleanIdeal.Setoid [I : BooleanIdeal] : Setoid (ℕ → ℕ) where
  r x y := {i | ¬(x i = y i)} ∈ I
  iseqv := {
    refl := by simp
    symm h := by simpa [eq_comm] using h
    trans {x} {y} {z} hxy hyz := by
      apply downward_closed (I.closed hxy hyz)
      grind
  }

@[simp] lemma BooleanIdeal.Setoid_rel_iff [I : BooleanIdeal] (x y : ℕ → ℕ) :
  x ≈ y ↔ {i | ¬(x i = y i)} ∈ I := Iff.rfl
